# Generated by Django 4.2.28 on 2026-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(help_text='e.g. Cloud Platform | DevOps | LLM Benchmarking', max_length=300),
        ),
    ]
