# Generated by Django 4.2.28 on 2026-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Public contact number shown on site (e.g. +9180...)', max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('cloud', 'Cloud Infrastructure'), ('iac', 'Infrastructure as Code'), ('containers', 'Containers & Kubernetes'), ('devops', 'DevOps Platforms'), ('python', 'Programming & Automation'), ('ai_llm', 'AI System Evaluation')], max_length=50),
        ),
    ]
