# Generated by Django 4.2.28 on 2026-03-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_profile_phone_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(help_text='Short bio used in the hero/intro (use blank lines to split paragraphs).', verbose_name='Opening bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_extended',
            field=models.TextField(blank=True, help_text='Detailed bio shown on the About section (optional).', verbose_name='About me (detailed)'),
        ),
        migrations.CreateModel(
            name='ProfileStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Years in tech, Certifications, Clients', max_length=80)),
                ('value', models.CharField(help_text='e.g. 5+, 12, 99.9%', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.profile')),
            ],
            options={
                'verbose_name': 'Profile Stat',
                'verbose_name_plural': 'Profile Stats',
                'ordering': ['order', 'id'],
            },
        ),
    ]
