# Generated by Django 4.2.29 on 2026-03-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_profile_about_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='applications_section_body',
            field=models.TextField(blank=True, default='', help_text='Describe the applications you have built or maintain. Supports plain text.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='applications_section_title',
            field=models.CharField(blank=True, default='Applications', help_text='Title for the applications detail section.', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='infra_diagram',
            field=models.ImageField(blank=True, help_text='Upload an infrastructure diagram or architecture image (optional).', null=True, upload_to='infra/', verbose_name='Infrastructure diagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='infra_section_body',
            field=models.TextField(blank=True, default='', help_text='Describe your infrastructure architecture and design decisions.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='infra_section_title',
            field=models.CharField(blank=True, default='Infrastructure & Architecture', help_text='Title for the infrastructure / architecture section.', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_heading_highlight',
            field=models.CharField(blank=True, default='engineered to scale.', help_text='Highlighted second line of the About heading.', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_heading_prefix',
            field=models.CharField(blank=True, default='Platform tooling and systems', help_text='First line of the About heading.', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_section_badge',
            field=models.CharField(blank=True, default='Tools & Architecture', help_text='Small label shown above the About heading.', max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_section_intro',
            field=models.CharField(blank=True, default='An overview of the tools, platforms, and architecture patterns I work with.', help_text='Short intro text shown under the About heading.', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_extended',
            field=models.TextField(blank=True, help_text='Detailed write-up shown in the Tools & Architecture section (optional).', verbose_name='Tooling & architecture details'),
        ),
    ]
