# Generated by Django 4.2.29 on 2026-03-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_profile_apps_infra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='show_in_hero',
            field=models.BooleanField(default=False, help_text='Enable to show this skill in the Hero tools strip.'),
        ),
    ]
