# Generated by Django 4.2.29 on 2026-03-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_skill_show_in_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Simple Icons slug (e.g. amazonaws, githubactions, terraform, docker).', max_length=100),
        ),
    ]
