# Generated by Django 4.2.29 on 2026-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blog_section_badge',
            field=models.CharField(blank=True, default='Writing', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='blog_section_intro',
            field=models.CharField(blank=True, default='Thoughts on AI, DevOps, cloud infrastructure and engineering.', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='blog_section_title',
            field=models.CharField(blank=True, default='Latest Posts', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='blog_view_all_label',
            field=models.CharField(blank=True, default='Read All Posts', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications_section_badge',
            field=models.CharField(blank=True, default='Credentials', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications_section_title',
            field=models.CharField(blank=True, default='Certifications', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_section_badge',
            field=models.CharField(blank=True, default='Contact', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_section_intro',
            field=models.CharField(blank=True, default="Send a message and I'll get back to you.", max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_section_title',
            field=models.CharField(blank=True, default="Let's Work Together", max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_section_badge',
            field=models.CharField(blank=True, default='Work History', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_section_intro',
            field=models.CharField(blank=True, default='Platform engineering and large-scale migrations.', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_section_title',
            field=models.CharField(blank=True, default='Experience', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_stats_label',
            field=models.CharField(blank=True, default='Quick stats', help_text='Heading shown above hero stats cards.', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_tools_label',
            field=models.CharField(blank=True, default='Core tools & services', help_text='Heading shown above hero tool chips.', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_empty_text',
            field=models.CharField(blank=True, default='Projects coming soon.', max_length=160),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_section_badge',
            field=models.CharField(blank=True, default='Portfolio', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_section_intro',
            field=models.CharField(blank=True, default='Large-scale migrations, automation frameworks, and full-stack systems built in production.', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_section_title',
            field=models.CharField(blank=True, default='Projects & Initiatives', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_view_all_label',
            field=models.CharField(blank=True, default='View All Projects', max_length=80),
        ),
    ]
