# Generated by Django 4.2.29 on 2026-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_profile_blog_section_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_upload',
            field=models.ImageField(blank=True, help_text='Upload a custom icon for brands not available on the CDN.', null=True, upload_to='skills/'),
        ),
    ]