# Generated by Django 4.2.29 on 2026-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_skill_icon_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]