# Generated by Django 4.2.29 on 2026-03-21 17:42

from django.db import migrations, models
from django.utils import timezone


def backfill_skill_updated_at(apps, schema_editor):
    Skill = apps.get_model('content', 'Skill')
    Skill.objects.filter(updated_at__isnull=True).update(updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_skill_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('context', models.CharField(blank=True, help_text='Optional app/system context (e.g. CI/CD platform, observability stack).', max_length=200)),
                ('tools', models.CharField(blank=True, help_text='Comma-separated tools/services (e.g. EKS, Jenkins, SonarQube, EC2).', max_length=400)),
                ('architecture', models.TextField(help_text='Deep details on architecture, workflows, and operational design.')),
                ('key_outcomes', models.TextField(blank=True, help_text='Optional outcomes, one per line.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Architecture Entry',
                'verbose_name_plural': 'Architecture Entries',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CurrentFocusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Current Focus Item',
                'verbose_name_plural': 'Current Focus Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Simple Icons slug (e.g. githubactions, terraform, docker). Leave blank if you upload a custom icon instead.', max_length=100),
        ),
        migrations.RunPython(backfill_skill_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
