# Generated by Django 4.2.29 on 2026-03-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_architectureentry_currentfocusitem_alter_skill_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectureentry',
            name='challenges_solutions',
            field=models.TextField(blank=True, help_text='Optional challenge and solution notes. Use one line per point.'),
        ),
        migrations.AddField(
            model_name='architectureentry',
            name='deployment_strategy',
            field=models.TextField(blank=True, help_text='Optional deployment strategy notes. One line per point.'),
        ),
        migrations.AddField(
            model_name='architectureentry',
            name='diagram_image',
            field=models.ImageField(blank=True, help_text='Optional architecture diagram image.', null=True, upload_to='architecture/'),
        ),
        migrations.AddField(
            model_name='architectureentry',
            name='diagram_text',
            field=models.CharField(blank=True, help_text='Optional textual flow (e.g. User -> React -> Django API -> Lambda -> MySQL).', max_length=500),
        ),
        migrations.AddField(
            model_name='architectureentry',
            name='integration_points',
            field=models.TextField(blank=True, help_text='Optional external integrations (mainframe, AWS services, third-party APIs). One line per point.'),
        ),
        migrations.AddField(
            model_name='architectureentry',
            name='performance_optimizations',
            field=models.TextField(blank=True, help_text='Optional optimization notes. Use one line per point.'),
        ),
        migrations.AddField(
            model_name='architectureentry',
            name='purpose',
            field=models.TextField(blank=True, help_text='What this application/tool does and its real-world use case.'),
        ),
    ]
