# Generated by Django 4.2.29 on 2026-03-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_architectureentry_challenges_solutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectureentry',
            name='architecture',
            field=models.TextField(blank=True, help_text='Deep details on architecture, workflows, and operational design (optional when diagram image is uploaded).'),
        ),
    ]
