# Generated by Django 4.2.29 on 2026-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_architectureentry_architecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolArchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('role', models.TextField(blank=True, default='')),
                ('setup', models.TextField(blank=True, default='')),
                ('usage', models.TextField(blank=True, default='')),
                ('communication', models.TextField(blank=True, default='')),
                ('tradeoffs', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Tool Architecture',
                'verbose_name_plural': 'Tool Architectures',
                'ordering': ['order', 'id'],
            },
        ),
    ]
