# Generated by Django 4.2.29 on 2026-03-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_toolarchitecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSourceContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('repository', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField()),
                ('contribution_type', models.CharField(blank=True, help_text='e.g. Feature, Bug Fix, Docs, Tooling', max_length=120)),
                ('contribution_date', models.DateField(blank=True, null=True)),
                ('contribution_url', models.URLField(blank=True)),
                ('tags', models.JSONField(default=list, help_text='List of tag strings')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Open Source Contribution',
                'verbose_name_plural': 'Open Source Contributions',
                'ordering': ['order', '-contribution_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='open_source_section_badge',
            field=models.CharField(blank=True, default='Open Source', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='open_source_section_intro',
            field=models.CharField(blank=True, default='Projects, fixes, and tooling contributions shared with the community.', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='open_source_section_title',
            field=models.CharField(blank=True, default='Open Source Contributions', max_length=200),
        ),
    ]
