# Generated by Django 4.2.29 on 2026-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_opensourcecontribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='architecture_caption',
            field=models.CharField(blank=True, help_text='Short caption shown under the architecture diagram.', max_length=240),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_diagram',
            field=models.ImageField(blank=True, help_text='Optional architecture/system diagram image for this project.', null=True, upload_to='projects/architecture/'),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_notes',
            field=models.TextField(blank=True, help_text='Detailed architecture explanation (components, flow, scaling, reliability).'),
        ),
    ]
