# Generated by Django 4.2.29 on 2026-03-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_project_architecture_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]